enum ReduxFileKey {
  SET_FILE_UPLOADED = 'SET_FILE_UPLOADED',
  RESET_FILE = 'RESET_FILE',
  SET_KEY_TO_SHARE_AND_ENCRYPT_FILE = 'SET_KEY_TO_SHARE_AND_ENCRYPT_FILE',
  SET_DECRYPTED_FILE = 'SET_DECRYPTED_FILE'
}

export default ReduxFileKey
