enum ReduxRequestKey {
  REQUEST_FETCHING = 'REQUEST_FETCHING',
  REQUEST_FAILURE = 'REQUEST_FAILURE',
  REQUEST_SUCCESS = 'REQUEST_SUCCESS',
  REQUEST_RESET_ALL = 'REQUEST_RESET_ALL'
}

export default ReduxRequestKey
